school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),

]

users/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
		path('', views.home, name='home'),
		path('login/', views.login, name='login'),
		path('register/', views.register, name='register'),
		path('logout/', views.logout, name='logout'),
		path('create/', views.create, name='create'),
		path('s_list/', views.s_list, name='s_list'),
		path('<int:id>/question/', views.question, name='question'),

		
		path('create/join_list', views.join_list, name='join_list'),

		path('<int:id>/title_list', views.title_list, name='title_list'),
		path('<int:id>/<int:val>/ques_list', views.ques_list, name='ques_list'),
		path('<int:id>/<int:value>/<int:pk>/delete', views.delete, name='delete'),

		path('teacher/', views.teacher, name='teacher'),
		path('create/t_t_list/<int:id>', views.t_t_list, name='t_t_list'),
		path('create/<int:s_id>/<int:id>/last', views.last, name='last'),


]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


templates/create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  
	<title></title>
  
</head>
<body >
  {% if messages %}
                       
                            {% for message in messages %}
                            <div class="alert alert-danger fade in" >
                                {{message}}
                            </div>
                            {% endfor %}
                        
                        {% endif %}
          <div ><h3>Your unique code is: {{code}}</h3></div>

          
            
        <a href="{% url 'users:logout' %}" align="right"><span>Logout</span></a>
      


	





        <div class="inner" align="center"> <h1 color="white"><u>Your Assignment titles</u></h1></div>
        <div class="container">
  <div class="row">
    
      
            {% for i in obj %}

            


              <div class="card" style="width: 18rem;">
                <a href="{% url 'users:question' i.id %}">

  <div class="card-body">
    <div class="col-sm">
    <h5 class="card-title">{{i.title}}</h5>
</div>
    
  </div>
</a>
</div>
               
            {% endfor %}
          </div></div>
        

<form method="post"> {% csrf_token %} 
{{form.as_p}}
<input type="submit" name="">
</form>
<a href="{% url 'users:logout' %}"><button>logout</button></a>
<a href=" {% url 'users:join_list' %} "><button>students who joined</button></a>




<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>OneSchool &mdash; Website by Colorlib</title>
    
    
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  
 
                <li><a href="{% url 'users:register' %}" class="nav-link">Register</a></li>
              
                
                  <form action="" method="post" class="form-box">
                    {% csrf_token %}
                    <h3 class="h4 text-black mb-4">Login</h3>
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Username" name="username" required>
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control" placeholder="Password" name="password" required>
                    </div>
                    
                    <div class="form-group">
                      <input type="submit" class="btn btn-primary btn-pill" value="Log in">
                    </div>
                  </form>

</body>
</html>

templates/join_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for i in list %}
<a href="{% url 'users:t_t_list' i.s_user_id  %}">{{i.s_user}}</a>

{% endfor%}
<a href="{% url 'users:create' %}"><button>go back</button></a>

</body>
</html>

templates/last.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for i in obj %}
	<img src="{{i.img.url}}" height="200" width="300" />
{% endfor %}
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
    <head>
       
      
        <title>Document</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->

    </head>
    <body >
        
          
                            <a href="{% url 'users:register' %}" class="signup-image-link"
                                >Create an account</a>
                       

                     {% if messages %}
                       
                            {% for message in messages %}
                            <div class="alert alert-danger fade in" >
                                {{message}}
                            </div>
                            {% endfor %}
                        
                        {% endif %}

                            <form
                                method="POST"
                                class="register-form"
                                id="login-form"
                            >
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="your_name"
                                        ><i
                                            class="zmdi zmdi-account material-icons-name"
                                        ></i
                                    ></label>
                                    <input
                                        type="text"
                                        name="username"
                                        id="your_name"
                                        placeholder="Your Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="your_pass"
                                        ><i class="zmdi zmdi-lock"></i
                                    ></label>
                                    <input
                                        type="password"
                                        name="password"
                                        id="your_pass"
                                        placeholder="Password"
                                    />
                                </div>
                                
                                <div class="form-group form-button">
                                    <input
                                        type="submit"
                                        name="signin"
                                        id="signin"
                                        class="form-submit"
                                        value="Log in"
                                    />
                                </div>
                            </form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

     
    </body>
    <!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>


templates/ques_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% for i in obj1 %}
	{% if i.img %}
	<img src="{{i.img.url}} " height="200" width="300" class="rounded float-left" /><a href=" {% url 'users:delete' i.id value pk %} ">delete</a><br>
	{% endif %}
	
	{% endfor%}<br>
{% for i in obj %}
{{i.ques}}<br>

{% endfor%}
<form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <input type="submit" name="submit" />
        </form>
<a href="{% url 'users:title_list' value %}"><button>go back</button></a>

</body>
</html>

templates/question.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for i in obj %}
{{i.ques}}

<br>
{% endfor%}
<a href="{% url 'users:create' %}"><button>go back</button></a>

<form method="post"> {% csrf_token %} 
{{form.as_p}}
<input type="submit" name="">


</form>
</body>
</html>

templates/r.html
{% load static %}
<!DOCTYPE html>
<html>
     <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Sign Up Form </title>

        <!-- Font Icon -->
        <link
            rel="stylesheet"
            href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}"
        />

        <!-- Main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body>
        <div class="main">
            <!-- Sign up form -->
            <section class="signup">
                <div class="container">
                    <div class="signup-content">
                        <div class="signup-form">
                            <h2 class="form-title">Sign up</h2>
                            <form
                                method="POST"
                                class="register-form"
                                id="register-form"
                            >
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="name"
                                        ><i
                                            class="zmdi zmdi-account material-icons-name"
                                        ></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="first_name"
                                        id="name"
                                        placeholder="Your First Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="last_name"
                                        ><i class="zmdi zmdi-account material-icons-name"></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="last_name"
                                        id="last_name"
                                        placeholder="Your Last Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="username"
                                        ><i
                                            class="zmdi zmdi-account material-icons-name"
                                        ></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="username"
                                        id="username"
                                        placeholder="Username"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="pass"
                                        ><i class="zmdi zmdi-lock"></i
                                    ></label>
                                    <input required
                                        type="password"
                                        name="password"
                                        id="pass"
                                        placeholder="Password"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="re-pass"
                                        ><i class="zmdi zmdi-lock-outline"></i
                                    ></label>
                                    <input required
                                        type="password"
                                        name="confirm"
                                        id="re_pass"
                                        placeholder="Repeat your password"
                                    />
                                </div>

                      			<div class="form-group">

                      				<label></label><br><br>
                      				{{my_form.as_p}}

							</div>








































                                

                                <div class="form-group form-button">
                                    <input
                                        type="submit"
                                        name="signup"
                                        id="signup"
                                        class="form-submit"
                                        value="Register"
                                    />
                                </div>
                            </form>
                        </div>
                        <div class="signup-image">
                            <figure>
                                <img
                                    src="{% static 'images/signup-image.jpg' %}"
                                    alt="sing up image"
                                />
                            </figure>
                            <a href="{% url 'users:login' %}" class="signup-image-link"
                                >I am already member</a
                            >
                        </div>
                    </div>
                </div>
            </section>
    </body>
</html>


templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
     <head>
        
        <title>Sign Up Form </title>

     
    </head>
    <body>
        {% if messages %}
                       
                            {% for message in messages %}
                            <div class="alert alert-danger fade in" >
                                {{message}}
                            </div>
                            {% endfor %}
                        
                        {% endif %}

        
                            <form
                                method="POST"
                                class="register-form"
                                id="register-form"
                            >
                            {% csrf_token %}
                                <div class="form-group">
                                    <label for="name"
                                        ><i
                                            class="zmdi zmdi-account material-icons-name"
                                        ></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="first_name"
                                        id="name"
                                        placeholder="Your First Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="last_name"
                                        ><i class="zmdi zmdi-account material-icons-name"></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="last_name"
                                        id="last_name"
                                        placeholder="Your Last Name"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="username"
                                        ><i
                                            class="zmdi zmdi-account material-icons-name"
                                        ></i
                                    ></label>
                                    <input required
                                        type="text"
                                        name="username"
                                        id="username"
                                        placeholder="Username"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="pass"
                                        ><i class="zmdi zmdi-lock"></i
                                    ></label>
                                    <input required
                                        type="password"
                                        name="password"
                                        id="pass"
                                        placeholder="Password"
                                    />
                                </div>
                                <div class="form-group">
                                    <label for="re-pass"
                                        ><i class="zmdi zmdi-lock-outline"></i
                                    ></label>
                                    <input required
                                        type="password"
                                        name="confirm"
                                        id="re_pass"
                                        placeholder="Repeat your password"
                                    />
                                </div>

                      			<div class="form-group">

                      				{{my_form.as_p}}

							</div>


                                <div class="form-group form-button">
                                    <input
                                        type="submit"
                                        name="signup"
                                        id="signup"
                                        class="form-submit"
                                        value="Register"
                                    />
                                </div>
                            </form>
                    
                            <a href="{% url 'users:login' %}" class="signup-image-link"
                                >I am already member</a
                            >
                        
    </body>
</html>


templates/s_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<form method="post"> {% csrf_token %} <h4 align="right"> Enter subject code to join<input type="text" name="code"><input type="submit" name="submit"></h4></form><br><br>


{% for i in oj %}
<a href=" {% url 'users:title_list' i.user_id %} "> 

<div class="card" style="width: 85rem;">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">{{i.subject}}</h6>
    <p class="card-text">{{i.name_to_display}}</p>
   
  </div>
</div>
</a> 





{% endfor%}

<a href="{% url 'users:logout' %}"><button>logout</button></a>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/t_t_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for i in obj %}
{{ i.title }} {{i.id }} <a href=" {% url 'users:last' s_id i.id %} "><button>SEE SOLUTION</button></a><br>
{% endfor %}
</body>
</html>

templates/teacher.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% if messages %}
                       
                            {% for message in messages %}
                            <div class="alert alert-danger fade in" >
                                {{message}}
                            </div>
                            {% endfor %}
                        
                        {% endif %}

	<form method="post">  {% csrf_token%} {{form.as_p}}
<input type="submit" name="">
	</form>

</body>
</html>

templates/title_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for i in obj %}
<a href=" {% url 'users:ques_list' i.id val %} ">{{i.title}} <br>{{i.id}}</a> 
<br>

{% endfor%}
<a href="{% url 'users:s_list' %}"><button>go back</button></a>

</body>
</html>